name: Create Unity Package

on: release

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: |
        find . -maxdepth 1 -name '*.meta' > metaList
        find docs/ Editor/ Tailwind/ -name '*.meta' >> metaList

    - run: mkdir a

    - uses: pCYSl5EDgo/create-unitypackage@master
      with:
        package-path: 'a/unity-tailwindcss.unitypackage'
        include-files: metaList

    - uses: actions/upload-artifact@v3
      with:
        path: a
        name: unitypackage

    # Create or attach to a release and upload the artifact
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v4
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        release_tag: ${{ github.ref }}
        asset_path: ./a/unity-tailwindcss.unitypackage
        asset_name: unity-tailwindcss.unitypackage
        asset_content_type: application/octet-stream
