name: Create Unity Package

on: release

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: |
        find . -maxdepth 1 -name '*.meta' > metaList
        find docs/ Editor/ Tailwind/ -name '*.meta' >> metaList

    - run: mkdir a

    - uses: pCYSl5EDgo/create-unitypackage@master
      with:
        package-path: 'a/unity-tailwindcss.unitypackage'
        include-files: metaList

    - uses: actions/upload-artifact@v2
      with:
        path: a
        name: unitypackage

    # Upload the unitypackage to the release
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./a/unity-tailwindcss.unitypackage
        asset_name: unity-tailwindcss.unitypackage
        asset_content_type: application/octet-stream
