name: Create Unity Package

on: release

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: |
        find . -maxdepth 1 -name '*.meta' > metaList
        find Documentation/ Editor/ Tailwind/ -name '*.meta' >> metaList

    - run: mkdir a

    - uses: pCYSl5EDgo/create-unitypackage@master
      with:
        package-path: 'a/TailwindCSS.unitypackage'
        include-files: metaList

    - uses: actions/upload-artifact@v4
      with:
        path: a
        name: unitypackage

    # Create a GitHub release and upload the asset
    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v2
      with:
        files: ./a//TailwindCSS.unitypackage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
